name: Tests
on: [push, pull_request]

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [6, 8.16.1, 10, 12]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install # switch to `npm ci` when Node.js 6.x is dropped
        env:
          CI: true

      - name: Run tests with coverage
        run: npm run test:cov
        if: startsWith(matrix.os, 'ubuntu')

      - name: Run tests without coverage
        run: npm test
        if: startsWith(matrix.os, 'windows')

      - name: Run Coveralls
        run: npm run coveralls
        if: matrix.node == 10 && startsWith(matrix.os, 'ubuntu') && github.repository == 'errorception/staticify' && github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
