name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [8.16.1, 10, 12]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:cov

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == 10 && startsWith(matrix.os, 'ubuntu')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
